# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lote', models.CharField(default=0, max_length=10, unique=True)),
                ('presentancion', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('sanitario', models.CharField(max_length=200)),
                ('fecha_expiracion', models.DateField()),
                ('fecha_produccion', models.DateField()),
                ('descripcion', models.TextField(max_length=400)),
                ('precio_Compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
