# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('ruc', models.IntegerField(unique=True)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=60)),
            ],
        ),
    ]
