# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_distribuidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('caracteristica', models.CharField(max_length=50)),
            ],
        ),
    ]
